from typing import Dict, List, Any, Sequence, TypedDict
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langgraph.graph import StateGraph, START, END
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field

# Define State
class AgentState(TypedDict):
    messages: Sequence[BaseMessage]
    question: str
    documents: List[Any] # Retrieved documents
    generation: str # Answer generated by the LLM
    citations: List[Dict[str, Any]] # Extracted source and page numbers
    iterations: int # Track number of reflection iterations

# Structured Output for Reflection Critique
class GradeAnswer(BaseModel):
    """Binary score to assess answer quality based on retrieved documents."""
    binary_score: str = Field(description="Answer addresses the user question based on context, 'yes' or 'no'")
    feedback: str = Field(description="Constructive critique if the answer does not address the question.")

class PDFAgent:
    """
    Orchestrates the retrieval and generation workflow using LangGraph and Groq LLaMA models.
    """
    
    def __init__(self, retriever_callable, max_iterations: int = 2, groq_api_key: str = None):
        self.retriever = retriever_callable
        self.max_iterations = max_iterations
        
        # Initialize Groq LLM (Ensure GROQ_API_KEY is set in env or passed)
        self.llm = ChatGroq(
            model="llama-3.1-8b-instant", 
            temperature=0, 
            api_key=groq_api_key
        )
        
        # Generator for answer
        self.generate_prompt = PromptTemplate(
            template="""You are an expert conversational AI assistant for questioning PDF documents.
            Use the following pieces of retrieved context to answer the question concisely and accurately.
            If you don't know the answer, just say that you don't know, don't try to make up an answer.
            
            Question: {question} 
            
            Context: {context} 
            
            Answer:""",
            input_variables=["question", "context"],
        )
        
        # Reflection generator
        self.reflect_prompt = PromptTemplate(
            template="""You are an expert grader assessing whether an AI generation addresses a user question.
            Based on the context retrieved, grade the generation.
            
            User Question: {question}
            
            Retrieved Context: {context}
            
            Agent Generation: {generation}
            
            Evaluate the generation. If it is high quality and completely addresses the question given the context, 
            score it 'yes'. Otherwise, score it 'no' and provide specific feedback on how to improve it.
            """,
            input_variables=["question", "context", "generation"]
        )
        
        self.improver_prompt = PromptTemplate(
            template="""You are an expert AI assistant tasked with improving an answer based on a grader's critique.
            Given the original question, retrieved context, previous answer, and critique, provide an improved answer.
            
            Question: {question} 
            
            Context: {context} 
            
            Previous Answer: {generation}
            
            Critique/Feedback: {feedback}
            
            Improved Answer:""",
            input_variables=["question", "context", "generation", "feedback"]
        )

        self.reflection_grader = self.llm.with_structured_output(GradeAnswer)
        self.graph = self._build_graph()
        
    def _build_graph(self) -> StateGraph:
        """
        Constructs the LangGraph state machine workflow.
        """
        workflow = StateGraph(AgentState)

        # Define nodes
        workflow.add_node("retrieve", self.retrieve_documents)
        workflow.add_node("generate", self.generate_answer)
        workflow.add_node("reflect", self.reflect_and_improve_answer)

        # Build graph execution
        workflow.add_edge(START, "retrieve")
        workflow.add_edge("retrieve", "generate")
        workflow.add_edge("generate", "reflect")
        
        # Conditional edge: continue improving or end
        workflow.add_conditional_edges(
            "reflect",
            self.decide_to_generate,
            {
                "useful": END,
                "not_useful": "generate"
            }
        )
        
        return workflow.compile()
        
    def retrieve_documents(self, state: AgentState) -> Dict:
        """
        Node: Retrieves relevant documents using the EnsembleRetriever.
        """
        print("---RETRIEVE---")
        question = state["question"]
        
        documents = self.retriever.invoke(question)
        
        # Extract citations
        citations = []
        for doc in documents:
             source = doc.metadata.get("source", "Unknown Source")
             page = doc.metadata.get("page", -1)
             if page != -1: page += 1 # 0-indexed to 1-indexed
             citations.append({"source": source, "page": page})
             
        # Remove duplicates from citations
        unique_citations = [dict(t) for t in {tuple(d.items()) for d in citations}]
             
        return {"documents": documents, "citations": unique_citations, "question": question}
        
    def generate_answer(self, state: AgentState) -> Dict:
        """
        Node: Generates the answer using the LLM. 
        If iterations > 0 and feedback exists in state (from reflect), uses improver prompt.
        """
        print("---GENERATE---")
        question = state["question"]
        documents = state["documents"]
        iterations = state.get("iterations", 0)
        feedback = state.get("feedback", "")
        
        # Join document content
        context = "\n\n".join([d.page_content for d in documents])
        
        if iterations == 0 or not feedback:
            # First pass generation
            prompt = self.generate_prompt.format(question=question, context=context)
        else:
            # Improvement pass
            generation = state.get("generation", "")
            prompt = self.improver_prompt.format(
                question=question, context=context, generation=generation, feedback=feedback
            )
            
        response = self.llm.invoke(prompt)
        # Update messages for history
        messages = list(state.get("messages", []))
        if iterations == 0:
            messages.append(HumanMessage(content=question))
        
        messages.append(AIMessage(content=response.content))
        
        return {"generation": response.content, "iterations": iterations, "messages": messages}
        
    def reflect_and_improve_answer(self, state: AgentState) -> Dict:
        """
        Node: Grades the generation using structured output.
        """
        print("---REFLECT---")
        question = state["question"]
        documents = state["documents"]
        generation = state["generation"]
        iterations = state["iterations"] + 1
        
        context = "\n\n".join([d.page_content for d in documents])
        prompt = self.reflect_prompt.format(question=question, context=context, generation=generation)
        
        # Invoke grader
        score_res = self.reflection_grader.invoke(prompt)
        
        print(f"Reflection Score: {score_res.binary_score.lower()}")
        print(f"Reflection Feedback: {score_res.feedback}")
        
        return {
            "iterations": iterations, 
            "grade": score_res.binary_score.lower(),
            "feedback": score_res.feedback
        }
        
    def decide_to_generate(self, state: AgentState) -> str:
        """
        Conditional Edge: Determines whether to loop back to generation based on grade.
        """
        grade = state.get("grade", "yes")
        iterations = state.get("iterations", 0)
        
        if grade == "yes" or iterations >= self.max_iterations:
            print("---DECISION: USEFUL or MAX ITERATIONS REACHED - ENDING---")
            return "useful"
        else:
            print("---DECISION: NOT USEFUL - RE-GENERATING---")
            return "not_useful"
            
    def run(self, question: str, chat_history: Sequence[BaseMessage] = None) -> Dict:
        """
        Entry point to invoke the agent.
        """
        if chat_history is None:
            chat_history = []
            
        initial_state = {
            "question": question,
            "messages": chat_history,
            "iterations": 0,
            "documents": [],
            "generation": "",
            "citations": [],
            "grade": "yes",
            "feedback": ""
        }
        
        result = self.graph.invoke(initial_state)
        return {
            "answer": result.get("generation", ""),
            "citations": result.get("citations", []),
            "chat_history": result.get("messages", []) # Return full history to be managed by client
        }
